"""History Table

Revision ID: 01b33b63b744
Revises: 11d33f4f6c56
Create Date: 2020-03-29 22:29:38.868522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b33b63b744'
down_revision = '11d33f4f6c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('state', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'state')
    # ### end Alembic commands ###
