"""History Table

Revision ID: 11d33f4f6c56
Revises: b28ad642fc94
Create Date: 2020-03-29 22:02:01.174561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d33f4f6c56'
down_revision = 'b28ad642fc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_history_location', table_name='history')
    op.create_index(op.f('ix_history_location'), 'history', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_location'), table_name='history')
    op.create_index('ix_history_location', 'history', ['location'], unique=1)
    # ### end Alembic commands ###
