"""assocaitions org and posts

Revision ID: 77ce474a475c
Revises: 0bd01e305fed
Create Date: 2020-03-25 00:28:37.563374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ce474a475c'
down_revision = '0bd01e305fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'organization_id')
    # ### end Alembic commands ###
