"""organization table

Revision ID: e508822313ca
Revises: f88509245587
Create Date: 2020-03-12 18:39:11.637598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e508822313ca'
down_revision = 'f88509245587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=64), nullable=True),
    sa.Column('founded_in', sa.String(length=120), nullable=True),
    sa.Column('official_email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_founded_in'), 'organization', ['founded_in'], unique=True)
    op.create_index(op.f('ix_organization_org_name'), 'organization', ['org_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_org_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_founded_in'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
